### ISSUE TITLE
The preview is not very clean

### ISSUE THREAD

**Issue by CedricJean** [UniversalDataTool/universal-data-tool#120]
A preview is the first impression of the user of how will be the interface to work with and is really important to catch his eye but our preview have a tendancy to be deformed when we reduce the size of the window 

![Capture](https://user-images.githubusercontent.com/63243979/81005455-f8f09900-8e1b-11ea-8907-e657b5c84973.PNG)
![image](https://user-images.githubusercontent.com/63243979/81005515-11f94a00-8e1c-11ea-8c98-b4571e76b56c.png)
![image](https://user-images.githubusercontent.com/63243979/81005557-24738380-8e1c-11ea-941a-42faa45b3e54.png)
![image](https://user-images.githubusercontent.com/63243979/81005584-33f2cc80-8e1c-11ea-9b73-3b3b51980580.png)

**Comment by seveibar** [comment]
Agreed, should hide description by default and the layout should probably modify to top/bottom instead of left/right at medium size screens.
