### ISSUE TITLE
Translations Infrastructure

### ISSUE THREAD

**Issue by seveibar** [UniversalDataTool/universal-data-tool#127]
Not sure what the best framework for this is, maybe [react-i18next](https://github.com/i18next/react-i18next)?

**Comment by CedricJean** [comment]
Do you think its possible to parse the string by a traduction server ?

**Comment by seveibar** [comment]
I think it's better to precompile and include the translations inside the application, we could absolutely use a translation server, but translations for static strings should be committed to the repository (unless there's something I'm missing)

**Comment by seveibar** [comment]
https://github.com/i18next/react-i18next

**Comment by seveibar** [comment]
fixed
