### ISSUE TITLE
Attempted import error: 'immerable' is not exported from 'immer'

### ISSUE THREAD

**Issue by mehmetilker** [UniversalDataTool/universal-data-tool#129]
After successful "npm install" on windows I got following exception when running project:

Failed to compile.

./node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js
Attempted import error: 'immerable' is not exported from 'immer'.

**Comment by seveibar** [comment]
@mehmetilker what node version are you using? We don't test often on windows, so it's very likely that the windows build is broken.

**Comment by mehmetilker** [comment]
It was 6.9.0 
I have upgraded to 6.14.5, same problem.

**Comment by seveibar** [comment]
I think that's your npm version, the most recent stable node version is 12. what do you get if you execute `node --version`?

**Comment by mehmetilker** [comment]
Oh, sorry, yes it was npm.
node version was 10.16.3
I have upgraded to v14.2.0 and now it works.
Tahnks.
