### ISSUE TITLE
The grid change if in label or in samples

### ISSUE THREAD

**Issue by CedricJean** [UniversalDataTool/universal-data-tool#135]
![image](https://user-images.githubusercontent.com/63243979/81416848-520c4580-9118-11ea-8a0b-6f32efc127d2.png)
![image](https://user-images.githubusercontent.com/63243979/81416882-5f293480-9118-11ea-8a21-5dc19844fc65.png)
In the first the blue one is a null annotation and the second is real annotation
The first one is add by the editing interface and the second by change file

**Comment by seveibar** [comment]
!! that's weird

**Comment by Ownmarc** [comment]
I noticed that too, Cedric, can you confirm its in both our fork and in the original repo ?

**Comment by CedricJean** [comment]
I confirm in the merge of them
I can't do the test using the original repo because AWS doesn't work
