### ISSUE TITLE
Could this be used to identify materials, not animals?

### ISSUE THREAD

**Issue by techybuddha** [UniversalDataTool/universal-data-tool#14]
Question quick. 

Do you think this could be used to identify materials? Like to determine a color or type of metal?

**Comment by seveibar** [comment]
Sure, I would recommend the data_entry interface.

![DeepinScreenshot_select-area_20200308102437](https://user-images.githubusercontent.com/1910070/76164626-caf61d80-6126-11ea-9564-a48d5473d30f.png)

**Comment by seveibar** [comment]
You can now use the image classification interface to accomplish this very easily
