### ISSUE TITLE
Named Entry Recognition doesn't change complete text when sample is changed

### ISSUE THREAD

**Issue by CedricJean** [UniversalDataTool/universal-data-tool#149]
The button complete don't switch the text when it sswitch sample

-- This issue affect Text Classification too !!!

**Comment by seveibar** [comment]
Hey @CedricJean, having a bit of trouble understanding this, are NER labels not saving?

**Comment by CedricJean** [comment]
I will do some print screen to show you

**Comment by CedricJean** [comment]
I start a project and i set one label : 
![image](https://user-images.githubusercontent.com/63243979/81954251-a1e68300-95d6-11ea-90d8-2b3e5e57bfcf.png)

I click on complete (the screen stay the same but i am on the other sample):
![image](https://user-images.githubusercontent.com/63243979/81954376-c6425f80-95d6-11ea-95e8-183eede07393.png)
the text should be change and the label too

I click on complete without anychange : 
![image](https://user-images.githubusercontent.com/63243979/81954588-07d30a80-95d7-11ea-8776-73af4975607e.png)
We see both label are labelled 

I click on the sample labelled 1 : 
![image](https://user-images.githubusercontent.com/63243979/81954738-3355f500-95d7-11ea-9ee0-692a0e2e31ef.png)
It all messed up the label is staying but it the right text this time

**Comment by seveibar** [comment]
Couldn't reproduce this, might have been fixed.
