### ISSUE TITLE
Typing a word in the labeling ID is very slow and Unresponsive (image segmentation) 

### ISSUE THREAD

**Issue by Wafaa-arbash** [UniversalDataTool/universal-data-tool#163]
<img width="1261" alt="Screen Shot 2020-05-21 at 10 57 39 AM" src="https://user-images.githubusercontent.com/59834878/82572099-e7183100-9b51-11ea-9c98-afc7054ae679.png">

**Comment by seveibar** [comment]
We shouldn't be rerendering "Options" on every character type

**Comment by seveibar** [comment]
@Wafaa-arbash we haven't been able to reproduce this again, could you let us know if it's still happening on the latest version>?

**Comment by Wafaa-arbash** [comment]
It worked this time with no issue, thanks

**Comment by seveibar** [comment]
@Wafaa-arbash is this fixed? Can I close?

**Comment by Wafaa-arbash** [comment]
Yes, it's all good now! thanks
