### ISSUE TITLE
The website hangs when opening a previously saved file

### ISSUE THREAD

**Issue by chestnut3108** [UniversalDataTool/universal-data-tool#176]
While importing the data I have encountered that page become unresponsive. Steps I have followed:-
1. Edited a NER task, saved the labelled file.
2. Opened the file in UDT to modify some labels.

The tab in chrome becomes totally unresponsive I have to kill the process. In the dev tools I am getting the following error hope it helps.

```
index.js:1 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in Unknown (at App.js:20)
    in ToastProvider (at App.js:19)
    in LabelHelpProvider (at App.js:18)
    in AuthProvider (at App.js:17)
    in AppConfigProvider (at App.js:16)
    in ThemeProvider (at Theme/index.js:21)
    in Unknown (at App.js:15)
    in App (at src/index.js:5) 
```

**Comment by seveibar** [comment]
Hey @chestnut3108, was this desktop or web? How many samples were in the dataset?

**Comment by chestnut3108** [comment]
Hi,

It was web version, I had annotated a small text file of about 250 words
for NER task. I reopened the file after downloading it in JSON format
because I wanted to modify some annotations, that's when I encountered this
issue.
