### ISSUE TITLE
Google drive is showing empty folders even-though they are not empty  

### ISSUE THREAD

**Issue by Wafaa-arbash** [UniversalDataTool/universal-data-tool#186]
I was trying to import a folder from my google drive, once I selected the folder, it shows "no item in this folder" 

<img width="997" alt="Screen Shot 2020-05-27 at 5 02 46 PM" src="https://user-images.githubusercontent.com/59834878/83071925-e55fd900-a03b-11ea-8170-6e8cf6d44024.png">

**Comment by seveibar** [comment]
When you're using the "Folders" filter, files won't show up
