### ISSUE TITLE
Uncaught TypeError  for Desktop app (win10)

### ISSUE THREAD

**Issue by twofish0319** [UniversalDataTool/universal-data-tool#188]
![image](https://user-images.githubusercontent.com/2947644/83113372-27e7eb00-a0fa-11ea-8beb-24c53c853fcf.png)

**Comment by seveibar** [comment]
thanks @twofish0319, what triggered the error? I see that `onClick` is in the chain of events so I'm wondering if this was triggered by clicking new file?

**Comment by twofish0319** [comment]
Yes, i click the "New File". But all template also start failed.
![image](https://user-images.githubusercontent.com/2947644/83208422-341a8980-a188-11ea-8349-ab4b8886cc65.png)

**Comment by ark-** [comment]
Same issue on 0.10.17 and 0.10.18. Errors as above but with my user path.

**Comment by ark-** [comment]
Worth adding nothing is clickable and therefore the app is completely unusable.

**Comment by chestnut3108** [comment]
I am also facing the same issue on Ubuntu, on 0.10.17.

**Comment by jay6621** [comment]
same here win 10 pro 64 bit, installed using installer.

**Comment by seveibar** [comment]
@jay6621 @chestnut3108 @ark- @twofish0319 Thank you all for reporting and the patience, I believe this issue has been resolved in version [v0.10.20](https://github.com/UniversalDataTool/universal-data-tool/releases/tag/v0.10.20)

![image](https://user-images.githubusercontent.com/1910070/85059194-db2b8900-b168-11ea-9bf0-299a38154ba0.png)
