### ISSUE TITLE
Feature: Video Annotation

### ISSUE THREAD

**Issue by seveibar** [UniversalDataTool/universal-data-tool#22]
We've heard some people ask for this, please thumbs up if you're interested!

Video annotation has some unique challenges. Labels should automatically interpolate between frames- e.g. if the user annotates frame 1 and 5 of a moving object, frames 2,3,4 should be automatically move the bounding box to different parts of the movement.

**Comment by Ownmarc** [comment]
Could also implement a few tracking algorithms and give the user the ability to customize his tracker using different filters (color, shape, background subtraction, etc.)

**Comment by seveibar** [comment]
That's a great idea!

I'm also wondering if each frame should be a sample, if we should "group" samples (e.g. 1.1, 1.2), or if the entire video should be a sample. Right now I'm thinking 1.1, 1.2 etc. would make sense

**Comment by seveibar** [comment]
the basic version of this is done, there are many enhancements that should be separate issues
