### ISSUE TITLE
Universal Data Tool Welcome Screen is crushed on Mobile

### ISSUE THREAD

**Issue by seveibar** [UniversalDataTool/universal-data-tool#235]
Should be responsive and stack contents using `<Grid />` from Material UI

![Screen Capture_select-area_20200729103452](https://user-images.githubusercontent.com/1910070/88813708-42385680-d187-11ea-9651-c4cd36c9fd4b.png)

**Comment by congdv** [comment]
Hi @seveibar , I'm working on this. However, I have an issue with the language selection button. By default, the button will be displayed in 'flex-end', so do you have any idea for change to 'flex-start' when the screen in XS mode.
![universal data tool](https://user-images.githubusercontent.com/8192210/91617432-10690a00-e956-11ea-82fd-6e58dde01f2a.png)
