### ISSUE TITLE
The Use Online tab on the home page looks like it is already selected 

### ISSUE THREAD

**Issue by cognitive137** [UniversalDataTool/universal-data-tool#284]
...and thus to use it Universal Data Tool, I started looking everywhere and clicked every link on the home page except "Use online". I think it would be more user friendly to not highlight it than highlighting it.

**Comment by seveibar** [comment]
@cognitive137 thanks!!! I'll change it today :)

**Comment by cognitive137** [comment]
HI @seveibar , I am a little new to open source, it the fix is easy can you please guide me through it, I want to change it.

**Comment by cognitive137** [comment]
Please.

**Comment by cognitive137** [comment]
I am hoping can can learn something in the process.

**Comment by cognitive137** [comment]
Hello, I have just sent a PR related to this issue, please take a look.

My apologies for taking this long.

**Comment by seveibar** [comment]
Thanks @cognitive137, here's a link to the PR for people watching https://github.com/UniversalDataTool/website/pull/3
