### ISSUE TITLE
Feature request: Pose estimation

### ISSUE THREAD

**Issue by AmitMY** [UniversalDataTool/universal-data-tool#285]
Any plans to support pose estimation in the future?
I imagine defining a pose, for example for the human body, dragging it on the picture, and then moving the joints to their location.

Any none visible joint should be allowed to be disabled, by double-clicking the joint or a keyboard shortcut.

**Comment by seveibar** [comment]
I'd love to do this!

**Comment by seveibar** [comment]
Are there any existing programs or user interfaces we could use for inspiration or to understand the problem better?

**Comment by Ownmarc** [comment]
For reference, its called key-point annotations or landmark annotations.

**Comment by AmitMY** [comment]
> Are there any existing programs or user interfaces we could use for inspiration or to understand the problem better?

thanks, for the quick response. 
I don't know any other program that has this feature. 


What I had in mind is like this:
![image](https://user-images.githubusercontent.com/5757359/92160860-5af7f400-ee38-11ea-93fb-eb0c635db8f1.png)


You define the left picture, as the pose (landmarks, and the connection between them, and maybe a templatic pose)
then in the right image, you drag this pose, on the image, and start moving the landmarks until they match.
(the limbs move along when you move a landmark, so they are always connected)

**Comment by seveibar** [comment]
Awesome! The feature will first need to be merged into [UniversalDataTool/react-image-annotate](https://github.com/UniversalDataTool/react-image-annotate)

**Comment by seveibar** [comment]
I bet we can do the pose definition in the Setup -> Configure page. Presumable you'd want to be able to drag the points as a group or individually. I'd imagine this is usually applied on videos? Is there a point in doing it for image datasets or can we just do video?

**Comment by seveibar** [comment]
Another example where they could have used Pose Estimation!
![Screen Capture_select-area_20200909091425](https://user-images.githubusercontent.com/1910070/92603089-e5978380-f27c-11ea-82a5-5132f00ca6c0.png)

**Comment by seveibar** [comment]
Landmark annotation is implemented and a JSON interface spec has been [proposed here](https://github.com/UniversalDataTool/udt-format/blob/master/interfaces/image_landmark_annotation.md).
