### ISSUE TITLE
Since v0.10.20 can't run desktop version properly. 

### ISSUE THREAD

**Issue by telemachor** [UniversalDataTool/universal-data-tool#293]
I've been using your desktop app v0.10.20 and tried to use new version. But when I launch it I see only white screen. Unlike [this issue](https://github.com/UniversalDataTool/universal-data-tool/issues/258) I have the same problem with internet.  I'm using kubuntu 19.10. Thank you for your help.

**Comment by seveibar** [comment]
Hey @telemachor thanks for reporting. I actually spent today working on this issue, can you try [v0.12.8](https://github.com/UniversalDataTool/universal-data-tool/releases/tag/v0.12.8)? I think it should work.

**Comment by telemachor** [comment]
@seveibar Thanks a lot for the quick bugfix. Everything is working great now.
