### ISSUE TITLE
Audio Transcription Interface is blank when reloading a configuration

### ISSUE THREAD

**Issue by seveibar** [UniversalDataTool/universal-data-tool#323]
For some reason the interface loads blank, even if i had previously clicked something!

To reproduce, just open an Audio Transcription template (e.g. on https://udt.dev or locally) and click Audio Transcription, then change some settings on the config page, navigate away and come back. It's always empty!

![image](https://user-images.githubusercontent.com/1910070/94280097-01f11c80-ff1b-11ea-8c9c-1b432ba2b8aa.png)

**Comment by anaplian** [comment]
I'd like to take a look at this :smile: 

Happy Hacktoberfest :jack_o_lantern:

**Comment by seveibar** [comment]
thanks @anaplian! looks good! Happy Hacktoberfest!

@all-contributors add @anaplian for code!
