### ISSUE TITLE
bug: unable to import text on Mac App

### ISSUE THREAD

**Issue by DSLituiev** [UniversalDataTool/universal-data-tool#33]
I am not able to import Directories or Test Snippets.

When I go Directory route, I can select a directory, but next it puts me to "Grid" view with nothing there.

If I press "Text Snippets", I can type, but I cannot paste any text from systems buffer (Cmd+V does not work, and there is no contextual menu).

I am using latest version downloaded 2020-03-23

**Comment by seveibar** [comment]
Thanks for reporting @DSLituiev! @puskuruk do you want to take a look at this? Otherwise I'm happy to dig in.

**Comment by puskuruk** [comment]
I'm looking! @seveibar
