### ISSUE TITLE
macOS builds beyond v0.13.2?

### ISSUE THREAD

**Issue by leonoverweel** [UniversalDataTool/universal-data-tool#338]
Hi, thanks for making UDT! I was wondering if there's a reason why there are no macOS `.dmg` installers for releases past v0.13.2? I installed that version and it prompts me to get v0.14.0, but there's no `.dmg` asset on that release.

**Comment by seveibar** [comment]
Most likely a problem with our build server, thanks for bringing it up! We plan on supporting MacOS into the future, the 0.14 release was just pretty big so a lot of small things broke, probably including the MacOS build!

**Comment by seveibar** [comment]
It seems v0.14.0 was just a fluke. v0.14.1 the mac dmg appears to be there!

![DeepinScreenshot_select-area_20201023142322](https://user-images.githubusercontent.com/1910070/97040027-619f0f80-153b-11eb-992e-f188328d879a.png)

**Comment by leonoverweel** [comment]
Thanks! I'll close this issue then :)

**Comment by illtellyoulater** [comment]
Any news on this?

**Comment by deepwilson** [comment]
This still seems unresolved.

**Comment by illtellyoulater** [comment]
I've lost any hope...
