### ISSUE TITLE
Multi-label image classification not working in UI

### ISSUE THREAD

**Issue by leonoverweel** [UniversalDataTool/universal-data-tool#349]
I've set up an image classification task where I set "Allow multiple labels per image?" to "Yes". However, UDT (14.1 on macOS and the web version) does not seem to recognize this: the UI looks the same sa it does for single-label classification, and even when I go back to images to add additional labels to them, only the latest one I click is preserved.

Here's my task specification:

```json
{
    "interface": {
        "type": "image_classification",
        "labels": [
            {
                "id": "simple",
            },
            {
                "id": "ignore",
            },
            {
                "id": "ambiguous",
            },
            {
                "id": "partial",
            }
        ],
        "multiple": true
    },
    "samples": []
}
```

It's hard to show in a screenshot, but any time I select one of these labels, it unselects the ones I've previously selected (and immediately goes to the next image, which is also not desirable for multi-label classification):

![image](https://user-images.githubusercontent.com/7980521/97292811-04150680-184c-11eb-95fd-1d96932390f5.png)

How do I get UDT to let me select multiple of labels for one image? Thanks.

**Comment by leonoverweel** [comment]
Possibly related issues: #276, #30.

**Comment by seveibar** [comment]
Thanks for reporting @leonoverweel! This code was refactored for v0.14.0 and I'm sure it's making sure that we don't programmatically go to next after clicking a classification!

**Comment by seveibar** [comment]
I've confirmed this bug as well
