### ISSUE TITLE
Files from Directory samples import broken on macOS/Windows/Probably Linux (v0.14.1)

### ISSUE THREAD

**Issue by leonoverweel** [UniversalDataTool/universal-data-tool#350]
When I try to import files from a directory on the latest version of the macOS app (v0.14.1), the samples do not appear in the UI after selecting the directory in the file browser. The files in question are PNG files. It did work in v0.13.2.

**Comment by seveibar** [comment]
Thanks for the report! I don't currently have a mac but I wonder if it's broken across other operating systems as well. I'll give it a try today and report back!

**Comment by thomasryck** [comment]
Some one I am working with have reported the same issue on v0.14.1 of the Windows version of the App. I can import the data he tried to import with v0.13.4 on Ubuntu.
