### ISSUE TITLE
Can't exit macOS app (v0.14.1) without force quit after starting a project

### ISSUE THREAD

**Issue by leonoverweel** [UniversalDataTool/universal-data-tool#351]
Once I open any project in v0.14.1 of the macOS app, I can't quit the app anymore without force quitting. This happens in every situation I've tried except for the launch screen, which does quit properly. This issue did not occur in v0.13.2.

**Comment by seveibar** [comment]
Didn't occur in v0.13.2? Weird regression and pretty important, thanks for reporting!

**Comment by leonoverweel** [comment]
As of the latest release I've tried (v0.14.9, sorry, took a while to try again), this problem is no longer happening :)
