### ISSUE TITLE
Sample number is not updating

### ISSUE THREAD

**Issue by jvdavim** [UniversalDataTool/universal-data-tool#354]
The current sample number on the top left corner of the labeling page is not updating.
![FirstImage](https://user-images.githubusercontent.com/16657663/97609755-c2729000-19f2-11eb-8011-b42cdcc901f1.png)
![SecondImage](https://user-images.githubusercontent.com/16657663/97609779-c9010780-19f2-11eb-8e2b-c1364736df08.png)
Probably a 0.14 bug.

**Comment by seveibar** [comment]
Thanks @jvdavim! Perfect timing, we're doing a bunch of development today in the hackathon :)

**Comment by seveibar** [comment]
Here's a reproduction: https://clips.twitch.tv/DarkLivelyGoblinMau5

**Comment by seveibar** [comment]
@all-contributors add @obrien-k for code
