### ISSUE TITLE
Fix Alignment of Star Button

### ISSUE THREAD

**Issue by seveibar** [UniversalDataTool/universal-data-tool#356]
See how they're not aligned? Is this bugging anyone else?

![image](https://user-images.githubusercontent.com/1910070/97626980-13898080-1a01-11eb-99cc-32944cf514db.png)

**Comment by lucas-barros** [comment]
I'll tackle this one

**Comment by AceroM** [comment]
![image](https://user-images.githubusercontent.com/21187304/97670288-457c0080-1a5c-11eb-8d3f-59a74a9b0e23.png)
looks fine to me

**Comment by seveibar** [comment]
It also appears different for me in Chrome

**Comment by seveibar** [comment]
*sigh* okay i guess this isn't very important, if it's bothering someone or someone knows what's going on feel free to chime in, closing until then. Thanks @AceroM  :)
