### ISSUE TITLE
[REFACTORING] Change color of writing

### ISSUE THREAD

**Issue by CedricProfessionnel** [UniversalDataTool/universal-data-tool#402]
**Description**
Change the color of the writing in the input of language in the home page (White would be good)

**Benefits**
It would prevent to write black on black

![Capture d’écran (2)](https://user-images.githubusercontent.com/74309042/101661370-32266280-3a16-11eb-9d80-3aa31f6eb896.png)

**Other Solution**
- Stay as is.
- Use an other color

**Comment by seveibar** [comment]
Do you mean the placeholder text or the dropdown text?

**Comment by CedricProfessionnel** [comment]
When you try writing in the text box at the top of the list box. Your writing color will change and it will be black on black. So i think its neither of the placeholder nor the dropdown text.
