### ISSUE TITLE
NER splits on letters with accents

### ISSUE THREAD

**Issue by Ownmarc** [UniversalDataTool/universal-data-tool#42]
I do not think the NER interface should split on letters with accents. Here are some really common in French "ùûàâçéèêëïîô"

![image](https://user-images.githubusercontent.com/24617457/78282400-39da5280-74ea-11ea-8dce-d45a374b84de.png)

**Comment by seveibar** [comment]
@Ownmarc that is correct it should not. I'll fix this ASAP- thanks for reporting

**Comment by Dzieni** [comment]
@seveibar just FYI, it still breaks on Polish. I've worked it around by changing a regex in the config to explicitly include those letters: `"wordSplitRegex": "[a-zA-ZÀ-ÿżźćńółęąśŻŹĆĄŚĘŁÓŃ]+"`. Maybe it's worth changing the default regex, although I'm not sure if there's a good "one size fits all" solution, especially considering non-Latin world.
