### ISSUE TITLE
Limit computer vision annotations to image frame

### ISSUE THREAD

**Issue by FlorianMF** [UniversalDataTool/universal-data-tool#426]
It would be cool if the UDT could ...
limit the possible image annotations (points, polygon, bounding boxes, landmarks) to its frame.

This would make life easier when annotating objects at the image borders. 

See the screenshot for an example of an annotation which does not make much sense, but is possible with UDT.

I used the Desktop installation for Windows 10 of version v0.14.16
![image](https://user-images.githubusercontent.com/57919375/103760115-9257f680-500c-11eb-9e23-cb21e2988c52.png)

**Comment by Ownmarc** [comment]
https://github.com/UniversalDataTool/universal-data-tool/issues/143
