### ISSUE TITLE
Highlight void annotation

### ISSUE THREAD

**Issue by FlorianMF** [UniversalDataTool/universal-data-tool#444]
It would be cool if the UDT could ...
highlight those samples which were seen but not annotated.
As of now, samples which the annotator opened but did not make an annotation for, are marked as annotated in the overview and the part ' "annotation:[], brush:"complete" ' is added to the udt.json file.

In my opinion, the sample should either highlighted as seen without annotation or not be marked as annotated at all.

**Comment by CedricProfessionnel** [comment]
Related to the dataset managers. Need to change the way to define if in the summary, the sample is or not annotated
