### ISSUE TITLE
Cannot find the executable in the release downloads

### ISSUE THREAD

**Issue by johann-petrak** [UniversalDataTool/universal-data-tool#453]
The documentation states that one can run the software on the desktop but there is no explanation how, or which file to actually run. https://docs.universaldatatool.com/installation

The releases seem to just contain the same directory as one gets when cloning the repo, and there is no linux appimage or similar to be found. 

Just to be sure I tried to run `npm install` (though I know nothing about npm or nodejs): 

The command `npm install` fails:
```
While resolving: universal-data-tool@0.14.22
Found: react@16.14.0
node_modules/react
  peer react@">= ^16.8.0" from react-data-table-component@6.9.7
  node_modules/react-data-table-component
    react-data-table-component@"^6.2.2" from the root project
  peer react@">= 16.8.0" from styled-components@5.1.1
  node_modules/styled-components
    styled-components@"^5.0.0" from the root project
    peer styled-components@">= ^3.2.3 || >= ^4.0.0 || >= ^5.0.0" from react-data-table-component@6.9.7
    node_modules/react-data-table-component
      react-data-table-component@"^6.2.2" from the root project

Could not resolve dependency:
peer react@"17.0.1" from react-dom@17.0.1
node_modules/react-dom
  peer react-dom@">= 16.8.0" from styled-components@5.1.1
  node_modules/styled-components
    styled-components@"^5.0.0" from the root project
    peer styled-components@">= ^3.2.3 || >= ^4.0.0 || >= ^5.0.0" from react-data-table-component@6.9.7
    node_modules/react-data-table-component
      react-data-table-component@"^6.2.2" from the root project
```

Tried this on Ubuntu 18.04 mit nvm/node/npm install manually using nvm as described here: https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/#2-installing-nodejs-and-npm

**Comment by johann-petrak** [comment]
OK, on an Ubuntu 20.04 with npm installed from the Ubuntu repos, i was able to run `npm install` but `npm build` failed.

**Comment by CedricProfessionnel** [comment]
Hi @johann-petrak ,

Can you send me your system information ? 
(OS, RAM ...)

I think i already encounter the reason why npm failed.

and for the command the command to launch the desktop app is :
(yarn or npm run) start:desktop
but now it have some issue so i propose to use 
(yarn or npm run) start

**Comment by seveibar** [comment]
Note that the current desktop build is failing, there are executables available for the v0.14.16 release.

![image](https://user-images.githubusercontent.com/1910070/107269627-dda06300-6a17-11eb-8c63-83a7a2b8ce47.png)

**Comment by seveibar** [comment]
We should make it so the release does not appear without those executables, or fix the build so that the executables are included.

**Comment by johann-petrak** [comment]
Hm, I have in the meantime changed my system configurations on all systems I tried this earlier.

Now on Ubuntu 18.04 with npm 7.4.3 version manually installed using nvm (instead of the version that comes as a system package), the installation with `npm install -g udt-collaboration-server` seemed to succeed ok. 

Then running `npm run start:desktop:static` from within the cloned and updated git repo gives this error:
```

> universal-data-tool@0.14.23 start:desktop:static
> electron ./desktop

sh: 1: electron: not found
npm ERR! code 127
npm ERR! path /data/johann/misc/GIT/universal-data-tool
npm ERR! command failed
npm ERR! command sh -c electron ./desktop
```
I tried to just do `npm install electron` but that failed and complained about being unable to resolve dependency tree.

**Comment by CedricProfessionnel** [comment]
You should have access to the .exe to  :
[https://github.com/UniversalDataTool/universal-data-tool/releases/download/v0.14.16/Universal-Data-Tool-Setup-0.14.16.exe](https://github.com/UniversalDataTool/universal-data-tool/releases/download/v0.14.16/Universal-Data-Tool-Setup-0.14.16.exe)

If it's not the version you wish, you can always go to :
[https://github.com/UniversalDataTool/universal-data-tool/releases](https://github.com/UniversalDataTool/universal-data-tool/releases)
and find the .exe of the version you wish

You can actually try to build from the source (like you do now), but I don't advised it.

**Comment by johann-petrak** [comment]
When I look at the https://github.com/UniversalDataTool/universal-data-tool/releases page, the only downloadable assets are a zip and a tar of the source code, no compiled programs or exes. As I am using Ubuntu (Linus) the exe is not much use, but I also cannot see a pre-compiled Linux app anywhere either. 
Oddly the link to the exe you gave works, however there is nothing shown on the release page that would link to the exe or any other executable.

**Comment by CedricProfessionnel** [comment]
As seveibar said, the build currently fails and therefore does not provide the .exe, but the link I sent you gives you the latest version whose build is successful. If you want to access via the release page, you must scroll down the page until you reach version 0.14.16 or a previous one.

**Comment by CedricProfessionnel** [comment]
![image](https://user-images.githubusercontent.com/74309042/107396625-ef434280-6acb-11eb-906d-466e8efb1cc3.png)

**Comment by johann-petrak** [comment]
Ah ok, so it appears the latest Linux appimage is from version 0.14.16

**Comment by illtellyoulater** [comment]
Guys... sorry to say but this is a total mess...
I'm a new user. 
The REAMDE here on the repo says:

> "Trying to run the web app locally? Run npm install then npm run start after cloning this repository to start the web server."

But when I try to do that, I get the following errors:

```
PS C:\Users\my-username\downloads\universal-data-tool-0.14.26> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: universal-data-tool@0.14.26
npm ERR! Found: webpack@5.72.1
npm ERR! node_modules/webpack
npm ERR!   peer webpack@">=2" from babel-loader@8.2.5
npm ERR!   node_modules/babel-loader
npm ERR!     peerOptional babel-loader@"^=8.x" from @cypress/react@4.16.4
npm ERR!     node_modules/@cypress/react
npm ERR!       dev @cypress/react@"^4.16.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional webpack@"^=3.x" from @cypress/react@4.16.4
npm ERR! node_modules/@cypress/react
npm ERR!   dev @cypress/react@"^4.16.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\my-username\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\my-username\AppData\Local\npm-cache\_logs\2022-05-27T01_31_09_817Z-debug-0.log
```

So what am I doing wrong? 
I'm on Windows 10, running node v16.15.0. 
I've rarely touched node so I have no idea about the severity of above issues, or whether or not they are expected in this release, or something else... t's just very frustrating... and I hope you can point me to the right direction....

Thanks!
