### ISSUE TITLE
Error in the Preview of text imported as JSON

### ISSUE THREAD

**Issue by saguillo2000** [UniversalDataTool/universal-data-tool#460]
![image](https://user-images.githubusercontent.com/47833532/107348660-9ec9e600-6ac7-11eb-8c83-dd46f756a006.png)

I don't know what is failing, may be is because the tool is not prepared by reading a JSON with sentences or I'm missing some paramter giving the length of each sentence. The structure of the JSON i'm giving is the next one:

![image](https://user-images.githubusercontent.com/47833532/107349038-097b2180-6ac8-11eb-8081-2496c9803aef.png)

Please if i'm doing sth wrong tell me

**Comment by CedricProfessionnel** [comment]
You're using the desktop or web app ?

**Comment by saguillo2000** [comment]
web app with docker to make it localhost

**Comment by CedricProfessionnel** [comment]
The UDT format is there :
[https://github.com/UniversalDataTool/udt-format](https://github.com/UniversalDataTool/udt-format)

an example of a whole project json:
{
  "name": "New undefined Dataset",
  "interface": {},
  "samples":  [
        {
          "document":"This strainer makes a great hat, I'll wear it while I serve spaghetti!",
        },
        {
          "document": "Why are all these dumpings covered in butter?!",
        }
      ],
}

If you wish to work with text samples you should familliarise yourself with **_Import Text Snippets_** for your first try

**Comment by CedricProfessionnel** [comment]
If it still failling after the change could you send me a reproducible example. So i can find the source of your error.
