### ISSUE TITLE
UDT "An error has occurred, details below" Windows Desktop Crashes

### ISSUE THREAD

**Issue by davodogster** [UniversalDataTool/universal-data-tool#461]
**The bug:**

Windows Desktop UDT. IT throws this error when I start up time series template and use the GUI to click on the tabs at the top.
![image](https://user-images.githubusercontent.com/46079516/107452083-787e7600-6bad-11eb-9120-551b75e141e3.png)
![image](https://user-images.githubusercontent.com/46079516/107452235-c1362f00-6bad-11eb-8ae8-260511aab665.png)

**Steps to Reproduce?**

Download .14.12 or .14.16 .exe file, install it (tried both). Select time series annotation, then click duration label, then click on JSON or 'Advanced'. Both give thsi error and the window has to be closed and UDT cannot be used as it always does this. Sometimes I can see things in all tabs including json / advanced but then next time I go on it the UDT crashes.

**Comment by CedricProfessionnel** [comment]
It currently fixed on a newer version, but in the newer version the desktop build fail so ... You will need to wait for the desktop build to be fixed.
