### ISSUE TITLE
 Image path universaldatatool/universaldatatool doesn't exist

### ISSUE THREAD

**Issue by antonkulaga** [UniversalDataTool/universal-data-tool#467]
Could not make singularity work:
```
ingularity run universaldatatool/universaldatatool
ERROR  : Image path universaldatatool/universaldatatool doesn't exist: No such file or directory
ABORT  : Retval = 255
```

**Comment by CedricProfessionnel** [comment]
Hi @antonkulaga , I would like to know what you're trying to do.

If you are trying to start the app use :
npm start

If you try to use singularity refer to the doc under :
https://singularity.lbl.gov/index.html 
https://github.com/hpcng/singularity
