### ISSUE TITLE
Can not find exe (for windows) for version 0.14.26

### ISSUE THREAD

**Issue by billalkuet07** [UniversalDataTool/universal-data-tool#539]
Hi,
I need to install newer version on windows platform. According to the "https://github.com/UniversalDataTool/universal-data-tool/wiki/Installation" guideline, I could not find exe file after download zip file. Where I can find the exe file for the latest release? Thanks in advance.

**Comment by seveibar** [comment]
the last version with an exe is here: https://github.com/UniversalDataTool/universal-data-tool/releases/tag/v0.14.17

**Comment by seveibar** [comment]
you may be able to build your own exe, but I don't use windows so I haven't been able to debug that release process

**Comment by billalkuet07** [comment]
thank you
