### ISSUE TITLE
Add contributing instruction

### ISSUE THREAD

**Issue by davebulaval** [UniversalDataTool/universal-data-tool#56]
In order to make contribution more clear I suggest a similar aproach:

https://github.com/facebook/draft-js/blob/a9316a723f9e918afde44dea68b5f9f39b7d9b00/CONTRIBUTING.md

Also for more clear Issue templating I recommand : https://github.com/GRAAL-Research/poutyne/tree/master/.github/ISSUE_TEMPLATE

I wanted to propose a PR but some point where not clear (linter, yapf).

**Comment by davebulaval** [comment]
If you like the template, I could just push it in a PR.

**Comment by seveibar** [comment]
Hey @davebulaval, the resources you've pointed to seem like a good starting point. We should put these files into the `.github` directory.

As far as the linting/formatting this project uses prettierv2, so you just need to run `npm run prettier` in the root directory to format all files prior to PRing.

You're welcome to submit a PR :)

**Comment by seveibar** [comment]
I've created a [guide for setting up the development server](https://github.com/UniversalDataTool/universal-data-tool/wiki/Setup-for-Development), which partially solves this issue. We could probably move it into the `.github` directory in the future.

**Comment by seveibar** [comment]
Hey @davebulaval did you want to try this? No worries if not :)

**Comment by davebulaval** [comment]
Will do this weekend.

**Comment by davebulaval** [comment]
For an update, Will do as soon as I finish my master thesis (should be in around 2-3 weeks).
