### ISSUE TITLE
Feature: Sample Colors / States

### ISSUE THREAD

**Issue by seveibar** [UniversalDataTool/universal-data-tool#58]
Many people have a pipeline where a machine learning sample can be in an "incomplete" "in review" and "complete" state. This feature should give flexibility for the user to determine the sample's state when saving in an efficient manner.

**Comment by Ownmarc** [comment]
Used alot when doing active learning!

**Comment by seveibar** [comment]
Initial version of this will be implemented with the [brush proposal](https://github.com/UniversalDataTool/udt-format/blob/master/proposals/sample_brushes.md)
