### ISSUE TITLE
stuck on github page in MacOS app -- cannot navigate back

### ISSUE THREAD

**Issue by DSLituiev** [UniversalDataTool/universal-data-tool#73]
I clicked Github button in the upper right corner in the Mac App, and now cannot get back to the labelling interface. There is a button in Navigate menu, but it does nothing:

<img width="219" alt="Screen Shot 2020-04-10 at 09 47 44" src="https://user-images.githubusercontent.com/8426290/79007682-86d4af00-7b10-11ea-978f-ce9074cee688.png">

**Comment by DSLituiev** [comment]
also tried other things like "new->empty" -- to no avail: still on the github page

**Comment by DSLituiev** [comment]
after closing the window and going again "new->empty" route raises this error:

<img width="427" alt="Screen Shot 2020-04-10 at 09 50 46" src="https://user-images.githubusercontent.com/8426290/79007812-d5824900-7b10-11ea-96e9-ed7f2dd204b9.png">

**Comment by seveibar** [comment]
Thanks @DSLituiev! We should never navigate away from the labeling page in the Mac app. I'll get this fixed.
